# Generated by Django 5.2 on 2025-04-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('search_name', models.CharField(max_length=255)),
                ('mbid', models.IntegerField(blank=True, max_length=50, null=True, unique=True)),
                ('lastfm_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artists')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.genre')),
            ],
        ),
        migrations.AddField(
            model_name='artists',
            name='gentre',
            field=models.ManyToManyField(through='artists.ArtistGenre', to='artists.genre'),
        ),
        migrations.AddIndex(
            model_name='artists',
            index=models.Index(fields=['search_name'], name='artists_art_search__64def6_idx'),
        ),
        migrations.AddIndex(
            model_name='artists',
            index=models.Index(fields=['lastfm_name'], name='artists_art_lastfm__1fbf27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artistgenre',
            unique_together={('artist', 'genre')},
        ),
    ]
